CXX = g++ -O3 -std=c++11

all: globalAssign  localAssign localAssignOrder localAssignDegree localAssignAcc localAssign_d1select_d2limit_Rlimit_diff_part_time

globalAssign : globalAssign.cpp
	$(CXX) -o globalAssign globalAssign.cpp
localAssign : localAssign.cpp
	$(CXX) -o localAssign localAssign.cpp
localAssignOrder : localAssignOrder.cpp
	$(CXX) -o localAssignOrder localAssignOrder.cpp
localAssignDegree : localAssignDegree.cpp
	$(CXX) -o localAssignDegree localAssignDegree.cpp
localAssignAcc : localAssignAcc.cpp
	$(CXX) -o localAssignAcc localAssignAcc.cpp
localAssign_d1select_d2limit_Rlimit_diff_part_time : localAssign_d1select_d2limit_Rlimit_diff_part_time.cpp
	$(CXX) -o localAssign_d1select_d2limit_Rlimit_diff_part_time localAssign_d1select_d2limit_Rlimit_diff_part_time.cpp
clean:
	rm -rf globalAssign  localAssign localAssignOrder localAssignDegree localAssignAcc localAssign_d1select_d2limit_Rlimit_diff_part_time